In [3]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
df = pd.read_csv('asso.csv')
df.head()

,milk,chips,bread,chocolate,butter,onion,tomato,oil,flour,cookies,gum,drink,fresh_juies,ice_cream,fries,meat
0,0,0,1,0,1,1,1,0,0,1,1,1,1,1,0,1
1,0,0,1,0,1,1,1,0,0,0,0,1,1,1,0,1
2,1,0,1,1,0,1,1,0,0,0,1,0,1,1,0,0
3,1,0,1,1,0,1,1,0,0,0,1,0,1,0,0,1
4,1,1,1,1,0,1,1,0,0,0,1,1,1,1,1,1

In [21]:
model= apriori(df, min_support=0.07, use_colnames=True)
rules = association_rules(model, metric="lift", min_threshold=2)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(bread, drink)",(butter),0.211494,0.418391,0.179310,0.847826,2.026398,0.090823,3.822003
1,(butter),"(bread, drink)",0.418391,0.211494,0.179310,0.428571,2.026398,0.090823,1.379885
2,"(butter, onion)",(drink),0.388506,0.425287,0.331034,0.852071,2.003518,0.165808,3.885057
3,"(drink, onion)",(butter),0.365517,0.418391,0.331034,0.905660,2.164628,0.178105,6.165057
4,(butter),"(drink, onion)",0.418391,0.365517,0.331034,0.791209,2.164628,0.178105,3.038838

In [22]:
rules[ (rules['lift'] >= 2) &
      (rules['confidence'] >= 0.8) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(bread, drink)",(butter),0.211494,0.418391,0.179310,0.847826,2.026398,0.090823,3.822003
2,"(butter, onion)",(drink),0.388506,0.425287,0.331034,0.852071,2.003518,0.165808,3.885057
3,"(drink, onion)",(butter),0.365517,0.418391,0.331034,0.905660,2.164628,0.178105,6.165057
6,"(butter, fresh_juies)",(drink),0.358621,0.425287,0.305747,0.852564,2.004678,0.153230,3.898051
7,"(fresh_juies, drink)",(butter),0.347126,0.418391,0.305747,0.880795,2.105196,0.160513,4.879055
...,...,...,...,...,...,...,...,...,...
3552,"(fresh_juies, drink, cookies, tomato, meat)","(butter, ice_cream, onion)",0.094253,0.370115,0.080460,0.853659,2.306469,0.045575,4.304215
3553,"(fresh_juies, drink, cookies, ice_cream, meat)","(butter, tomato, onion)",0.096552,0.360920,0.080460,0.833333,2.308917,0.045612,3.834483
3566,"(fresh_juies, butter, cookies, onion, meat)","(drink, ice_cream, tomato)",0.096552,0.356322,0.080460,0.833333,2.338710,0.046056,3.862069
3568,"(fresh_juies, butter, cookies, tomato, meat)","(drink, ice_cream, onion)",0.091954,0.351724,0.080460,0.875000,2.487745,0.048117,5.186207
3569,"(fresh_juies, butter, cookies, ice_cream, meat)","(tomato, drink, onion)",0.098851,0.342529,0.080460,0.813953,2.376307,0.046601,3.533908

In [26]:
data=pd.read_csv('admission.csv')
data.head(1)
x=data.iloc[:,[1,2,3,6,7]]
y=data.iloc[:,8]

In [31]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn import metrics
param_grid = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001]} 
grid = GridSearchCV(SVC(),param_grid)
grid.fit(x,y)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [32]:
grid.get_params

<bound method BaseEstimator.get_params of GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)>

In [34]:
y_pred=grid.predict(x)
print(metrics.accuracy_score(y,y_pred))

0.87

In [35]:
from sklearn.model_selection import cross_val_score

In [40]:
from sklearn import model_selection
x=data.iloc[:,1:8]
y=data.iloc[:,8]
x_train,x_test,y_train,y_test=model_selection.train_test_split(x,y,test_size=0.3,random_state=1)
k_fold=model_selection.KFold(n_splits=5,random_state=1)
from sklearn import tree
model=tree.DecisionTreeClassifier()
results=model_selection.cross_val_score(model,x_train,y_train,cv=k_fold)
print(results)

[0.8        0.82857143 0.74285714 0.68571429 0.78571429]

D:\anaconda\lib\site-packages\sklearn\model_selection\_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning